name: Deploying Hugo Site to GitHub Pages

on:
  # Trigger the workflow on push to the main branch or manual runs
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # Use the latest Hugo version

      # Step 3: Initialize Git submodules (required for Archie theme)
      - name: Initialize Git Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      # Step 4: Build the site
      - name: Build Site
        run: hugo --minify

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages         # Deployment branch
          publish_dir: ./public            # Hugo's output directory
          cname: mathapriori.github.io     # Your custom domain (GitHub Pages URL)
